create extension if not exists "pgcrypto";
create table public.categories (id uuid primary key default gen_random_uuid(), nom text not null, slug text unique not null, icone text, description text, created_at timestamptz default now());
create table public.offres (id uuid primary key default gen_random_uuid(), titre text not null, description text not null, structure_nom text not null, categorie_id uuid references public.categories(id), localisation text, date_limite date, lien_candidature text, email_contact text, image_url text, details jsonb default '{}'::jsonb, statut text not null default 'pending' check (statut in ('pending','approved','rejected','archived')), created_at timestamptz default now(), constraint moyen_candidature check (lien_candidature is not null or email_contact is not null));
create table public.ressources (id uuid primary key default gen_random_uuid(), titre text not null, description text, url text not null, type text not null check (type in ('cv','formation_certifiante')), prix text check (prix in ('gratuit','payant')), created_at timestamptz default now());
insert into public.categories (nom,slug,icone,description) values ('Bourses d’études','bourses','🎓','Financer ses études'),('Formations','formations','🏫','Développer ses compétences'),('Concours','concours','🏆','Se challenger et révéler ses talents'),('Emplois','emplois','💼','Construire son expérience professionnelle'),('Stages','stages','🔬','Apprendre sur le terrain'),('Programmes et opportunités','programmes','🌍','Élargir ses horizons');
alter table public.categories enable row level security; alter table public.offres enable row level security; alter table public.ressources enable row level security;
create policy "categories_select_public" on public.categories for select using (true); create policy "categories_manage_authenticated" on public.categories for all to authenticated using (true) with check (true);
create policy "offres_select_approved_public" on public.offres for select using (statut = 'approved' or auth.role() = 'authenticated'); create policy "offres_insert_pending_public" on public.offres for insert to anon,authenticated with check (statut = 'pending'); create policy "offres_manage_authenticated" on public.offres for update,delete to authenticated using (true) with check (true);
create policy "ressources_select_public" on public.ressources for select using (true); create policy "ressources_manage_authenticated" on public.ressources for all to authenticated using (true) with check (true);
